{% set name = "libi2c" %}
{% set version = "4.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://www.kernel.org/pub/software/utils/i2c-tools/i2c-tools-{{ version }}.tar.xz
    sha256: 8b15f0a880ab87280c40cfd7235cfff28134bf14d5646c07518b1ff6642a2473

build:
  skip: true  # [not linux]
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - test -f ${PREFIX}/include/i2c/smbus.h
    - test -f ${PREFIX}/lib/libi2c.so

about:
  home: https://i2c.wiki.kernel.org/index.php/I2C_Tools
  license: LGPL-2.1-or-later
  license_file: COPYING.LGPL
  summary: Library part of i2c-tools package for i2c access on Linux.

extra:
  recipe-maintainers:
    - traversaro
